name: SkyCraft
main: org.mad3ngineer.SkyCraft
depend: [WorldEdit,CleanroomGenerator,WorldGuard,SQLibrary]
version: ${project.version}

commands:
   island:
      description: Island Operations.
      usage: /island [home|sethome|accept|decline|delete] {[invite|kick|visit|] <player>}
      permission: skycraft.island
      permission-message: You don't have <permission>
   islandev:
      description: Admin Island Operations.
      usage: /islandev [tp|delete] <player> {transfer <owner> <newowner>}
      
permissions:
    skycraft.*:
        description: Gives access to all skycraft commands
        children:
            skycraft.island.*: true
            skycraft.islandev.*: true
    skycraft.island.*:
        description: Gives access to all user commands
        children:
            skycraft.island.home: true
            skycraft.island.sethome: true
            skycraft.island.visit: true
            skycraft.island.visitable: true
            skycraft.island.create: true
            skycraft.island.accept: true
            skycraft.island.decline: true
            skycraft.island.kick: true
            skycraft.island.delete: true
            skycraft.island.create: true
            skycraft.island: true
    skycraft.island.home:
        description: Go to island
        default: true
    skycraft.island.sethome:
        description: Set island home
        default: true
    skycraft.island.visit:
        description: Visit someone's island
        default: true
    skycraft.island.visitable:
        description: Toggle your islands visitability
        default: true
    skycraft.island.accept:
        description: Accept invite to island
        default: true
    skycraft.island.decline:
        description: Decline island invite
        default: true
    skycraft.island.kick:
        description: Kick a player from your island
        default: true
    skycraft.island.delete:
        description: Delete your island
        default: true
    skycraft.island.create:
        description: Create a new island
        default: true
    skycraft.islandev.*:
        description: Gives access to all admin commands
        default: op
        children:
            skycraft.islandev.tp: true
            skycraft.islandev.transfer: true
            skycraft.islandev.delete: true
    skycraft.islandev.tp:
        description: Teleport to players islands
        default: op
    skycraft.islandev.transfer:
        description: Transfer island ownership
        default: op
    skycraft.islandev.delete:
        description: Force island deletion
        default: op